# INTERFAZ DE USUARIO INICIAL PARA UN INVENTARIO DE LIBROS
# TITULO, NOMBRE DEL ALGORITMO, NOMBRE DEL PROGRAMA.
print("\n") #SALTA UNA LINEA (COMO DAR ENTER)
print("----- INVENTARIO DE LIBROS -----") 
print("\nProductos disponibles:")  
print("\nAtravez de mi ventana / El principito / Culpa mia")

# SOLICITAR AL USUARIO QUE INGRESE EL NOMBRE, PRECIO Y CANTIDAD DEL PRODUCTO.
# CREAMOS UNA VARIABLE PARA CADA DATO QUE VAMOS A SOLICITAR AL USUARIO, Y UTILIZAMOS LA FUNCION input() PARA OBTENER LOS DATOS INGRESADOS POR EL USUARIO.
# TAMBIEN AGREGAMOS UN CICLO "while" PARA VALIDAR QUE EL USUARIO INGRESE UN NOMBRE DEL PRODUCTO, UN PRECIO Y UNA CANTIDAD VALIDOS (QUE SEAN NUMEROS POSITIVOS).

nombre_producto = input("\nIngrese el nombre del libro: ")

while True: # UTILIZAMOS UN CICLO "while" PARA VALIDAR QUE EL USUARIO INGRESE UN NUMERO POSIVO PARA EL PRECIO DEL LIBRO.
    try:
        precio_producto = float(input("\nIngrese el precio del libro: ")) # UTILIZAMOS float() PARA CONVERTIR EL DATO INGRESADO POR EL USUARIO A UN NUMERO DECIMAL, YA QUE EL PRECIO PUEDE TENER DECIMALES.
        if precio_producto <= 0: # VALIDAMOS QUE EL PRECIO SEA UN NUMERO POSITIVO, SI EL USUARIO INGRESA UN NUMERO NEGATIVO O CERO, MOSTRAMOS UN MENSAJE DE ERROR Y VOLVEMOS A SOLICITAR EL PRECIO HASTA QUE INGRESE UN DATO VALIDO.
            print("Por favor, ingrese un precio válido (número positivo).") # VOLVEMOS A SOLICITAR AL USUARIO QUE INGRESE EL PRECIO HASTA QUE INGRESE UN DATO VALIDO.
        else: 
            break # SI EL DATO ES VALIDO, SALIMOS DEL CICLO
    except ValueError:
        print("Por favor, ingrese un precio válido (númeroa.")

while True:
    try:
        cantidad_producto = int(input("\nIngrese la cantidad de libros: ")) # UTILIZAMOS int() PARA CONVERTIR EL DATO INGRESADO POR EL USUARIO A UN NUMERO ENTERO, YA QUE LA CANTIDAD DEBE SER UN NUMERO ENTERO.
        if cantidad_producto <= 0: # VALIDAMOS QUE LA CANTIDAD SEA UN NUMERO POSITIVO, SI EL USUARIO INGRESA UN NUMERO NEGATIVO O CERO, MOSTRAMOS UN MENSAJE DE ERROR Y VOLVEMOS A SOLICITAR LA CANTIDAD HASTA QUE INGRESE UN DATO VALIDO.
            print("Por favor, ingrese una cantidad válida (número positivo).")
        else:
            break # SI EL DATO ES VALIDO, SALIMOS DEL CICLO
    except ValueError: # SI EL USUARIO INGRESA UN DATO QUE NO ES UN NUMERO, SE GENERA UNA EXCEPCION ValueError, Y MOSTRAMOS UN MENSAJE DE ERROR.
        print("Por favor, ingrese una cantidad válida (número entero).") # VOLVEMOS A SOLICITAR AL USUARIO QUE INGRESE LA CANTIDAD HASTA QUE INGRESE UN DATO VALIDO.
